# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fort Greene Open Streets Coalition
email: info@fortgreeneopenstreets.org
description: >- # this means to ignore newlines until "baseurl:"
  We're a group of neighbors who are taking over administration of the Open Streets program in and around Fort Greene, Brookyln. We will manage the open streets on Willoughby Ave, South Portland St, Hall St and hopefully North Elliott Place. These streets are closed to cars, and open to people, from 8am to 8pm every day.

url: "https://www.fortgreeneopenstreets.org"

# Build settings
theme: minima
plugins:
  - jekyll-feed

site:
  social:
    - icon: twitter
      url: twitter.com/fgopenstreets
      name: Twitter
    - icon: instagram
      url: instagram.com/fortgreeneopenstreets
      name: Instagram
    - icon: facebook
      url: facebook.com/fortgreeneopenstreets
      name: Facebook
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
